#!/bin/bash
cp fonts.conf ~/Downloads

echo "Downloading MS Gothic and MS Mincho..."
rm msgothic.zip msmincho.zip MSGOTHIC.TTF MSMINCHO.TTF
wget http://www.linux.ryukent.co.uk/download/msgothic.zip
wget http://www.linux.ryukent.co.uk/download/msmincho.zip
unzip msgothic.zip
unzip msmincho.zip

echo "Moving fonts to /usr/share..."
mkdir ~/.fonts
mkdir ~/.fonts/msjapanese
rm msgothic.zip msmincho.zip
mv MSGOTHIC.TTF ~/.fonts/msjapanese
mv MSMINCHO.TTF ~/.fonts/msjapanese

echo "Backing up /etc/fonts/fonts.conf"
cp ~/.fonts.conf ~/.fonts.conf.bak

echo "Copying fonts.conf to /etc/fonts/fonts.conf"
cp fonts.conf ~/.fonts.conf
sudo fc-cache -f -v
